services:
  postgres:
    container_name: prisma-postgres
    image: postgres:15.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ../.test:/init
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: sandbox
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
